"""
The Grafana dashboard JSON is generated by monitoring/grafana/build_dashboard.py.
These tests keep the committed JSON and its generator in step, and check
that every panel queries a metric the app actually exports.
"""

import importlib.util
import json
import re
from pathlib import Path

from fastapi.testclient import TestClient

from semcache.main import app

ROOT = Path(__file__).parent.parent
BUILDER = ROOT / "monitoring" / "grafana" / "build_dashboard.py"
DASHBOARD = ROOT / "monitoring" / "grafana" / "dashboards" / "semcache.json"


def _builder():
    spec = importlib.util.spec_from_file_location("build_dashboard", BUILDER)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_committed_dashboard_matches_its_generator():
    assert DASHBOARD.read_text(encoding="utf-8") == _builder().render(), (
        "Run: uv run python monitoring/grafana/build_dashboard.py"
    )


def test_panels_fit_the_grid_without_overlapping():
    panels = json.loads(DASHBOARD.read_text(encoding="utf-8"))["panels"]
    cells = set()
    for panel in panels:
        pos = panel["gridPos"]
        assert pos["x"] + pos["w"] <= 24, panel["title"]
        for x in range(pos["x"], pos["x"] + pos["w"]):
            for y in range(pos["y"], pos["y"] + pos["h"]):
                assert (x, y) not in cells, f"{panel['title']} overlaps another panel"
                cells.add((x, y))
    assert len({p["id"] for p in panels}) == len(panels)


def test_every_panel_queries_metrics_the_app_exports():
    """A renamed or removed metric would silently leave a panel empty."""
    # Declared metrics ("# TYPE name kind"); present even before any data.
    declared = set(re.findall(r"^# TYPE (semcache_\w+)", TestClient(app).get("/metrics").text, re.MULTILINE))
    # Counters are declared without the "_total" suffix their samples carry.
    exported = declared | {f"{name}_total" for name in declared}

    panels = json.loads(DASHBOARD.read_text(encoding="utf-8"))["panels"]
    for panel in panels:
        for target in panel["targets"]:
            for metric in re.findall(r"semcache_\w+", target["expr"]):
                base = re.sub(r"_(bucket|count|sum)$", "", metric)
                assert metric in exported or base in exported, f"{panel['title']}: {metric} is not exported"
