"""
Cache administration endpoints: live stats and invalidation.

WHY INVALIDATION?
    Changing a system prompt or a model name already changes the cache
    namespace, so stale entries can never be *served*; they just sit there
    until their TTL expires. Invalidation matters when the answers go stale
    while the request stays the same:
      - A model is upgraded behind the same name (e.g. a "-latest" alias).
      - Facts changed (a price, a policy) and cached answers are now wrong.
      - A feature's cached answers should be reset as a group (by tag).
    It also frees memory from namespaces that will never be used again.
"""

import secrets
from datetime import timedelta
from typing import Annotated

from fastapi import APIRouter, Depends, Header, HTTPException, Query
from pydantic import BaseModel, Field, model_validator

from semcache.api.dependencies import get_engine
from semcache.cache.engine import CacheEngine
from semcache.cache.keys import hash_system_prompt, normalize_cache_tag
from semcache.cache.store.base import EntryFilter
from semcache.cache.store.redis_store import KEY_PREFIX
from semcache.config import Settings, get_settings

router = APIRouter()


def require_admin(
    settings: Annotated[Settings, Depends(get_settings)],
    authorization: Annotated[str | None, Header()] = None,
) -> None:
    """Require the admin bearer token, when ADMIN_TOKEN is configured."""
    if settings.admin_token is None:
        return
    expected = f"Bearer {settings.admin_token}"
    if authorization is None or not secrets.compare_digest(authorization, expected):
        raise HTTPException(
            status_code=401,
            detail="Invalid or missing admin token.",
            headers={"WWW-Authenticate": "Bearer"},
        )


class InvalidateRequest(BaseModel):
    """
    Which entries to invalidate. Filters are combined with AND.

    To clear the whole cache, send {"all": true} and no filters, so that an
    empty or mistyped request can never wipe everything by accident.
    """

    model: str | None = Field(default=None, description="Entries generated by this model.")
    system_prompt: str | None = Field(
        default=None,
        description='Entries for this exact system prompt ("" = requests without one).',
    )
    system_prompt_hash: str | None = Field(
        default=None, description="Same as system_prompt, by its 16-char hash."
    )
    tag: str | None = Field(default=None, description="Entries labelled with this tag.")
    tag_prefix: str | None = Field(
        default=None, description='Entries with a tag starting with this (e.g. "billing:").'
    )
    all: bool = Field(default=False, description="Clear every entry. Cannot be combined with filters.")
    dry_run: bool = Field(default=False, description="Only count the matching entries.")

    @model_validator(mode="after")
    def _validate(self) -> "InvalidateRequest":
        if self.system_prompt is not None and self.system_prompt_hash is not None:
            raise ValueError("Give system_prompt or system_prompt_hash, not both.")
        if self.model is not None and not self.model.strip():
            raise ValueError("model must not be empty.")
        if self.system_prompt_hash is not None:
            h = self.system_prompt_hash.lower()
            if len(h) != 16 or any(c not in "0123456789abcdef" for c in h):
                raise ValueError("system_prompt_hash must be 16 hex characters.")
            self.system_prompt_hash = h
        if self.tag is not None:
            self.tag = normalize_cache_tag(self.tag)
        if self.tag_prefix is not None:
            self.tag_prefix = normalize_cache_tag(self.tag_prefix)
            if len(self.tag_prefix) < 2:
                # Redis prefix queries need at least 2 characters.
                raise ValueError("tag_prefix must be at least 2 characters.")

        has_filter = not self.to_filter().is_empty()
        if self.all and has_filter:
            raise ValueError('"all" cannot be combined with filters.')
        if not self.all and not has_filter:
            raise ValueError('Give at least one filter, or {"all": true} to clear the whole cache.')
        return self

    def to_filter(self) -> EntryFilter:
        system_prompt_hash = self.system_prompt_hash
        if self.system_prompt is not None:
            system_prompt_hash = hash_system_prompt(self.system_prompt)
        return EntryFilter(
            model=self.model,
            system_prompt_hash=system_prompt_hash,
            tag=self.tag,
            tag_prefix=self.tag_prefix,
        )


@router.get("/stats")
async def get_stats(engine: CacheEngine = Depends(get_engine)):  # noqa: B008
    """
    Get live cache state.
    """
    stats = await engine.stats()
    return stats


@router.get("/entries", dependencies=[Depends(require_admin)])
async def list_entries(
    engine: Annotated[CacheEngine, Depends(get_engine)],
    limit: Annotated[int, Query(ge=1, le=200)] = 50,
) -> dict:
    """
    The most recently cached entries, newest first.

    Admin-only: entries hold other users' prompts and answers.
    """
    entries = await engine.list_entries(limit)
    return {
        "entries": [
            {
                "id": entry.id.removeprefix(KEY_PREFIX),
                "prompt": entry.prompt,
                "response": entry.response,
                "model": entry.model,
                "tags": entry.tags,
                "system_prompt_hash": entry.system_prompt_hash,
                "created_at": entry.created_at.isoformat(),
                "expires_at": (entry.created_at + timedelta(seconds=entry.ttl_seconds)).isoformat(),
                "ttl_seconds": entry.ttl_seconds,
                "hit_count": entry.hit_count,
                "required_similarity": entry.required_similarity,
                "usage": (entry.response_metadata or {}).get("usage"),
            }
            for entry in entries
        ]
    }


@router.post("/invalidate", dependencies=[Depends(require_admin)])
async def invalidate(
    request: InvalidateRequest,
    engine: Annotated[CacheEngine, Depends(get_engine)],
) -> dict:
    """
    Delete the cache entries matching the filters (or count them, with dry_run).

    Examples:
      {"model": "gemini-3.5-flash"}                 after a model upgrade
      {"system_prompt": "You are a support agent."} after changing that prompt
      {"tag": "pricing"}                            after prices changed
      {"tag_prefix": "billing:", "dry_run": true}   see what would be cleared
      {"all": true}                                 clear the whole cache
    """
    entry_filter = request.to_filter()
    applied = entry_filter.as_dict() or {"all": True}

    if request.dry_run:
        return {"dry_run": True, "matched": await engine.count(entry_filter), "filter": applied}

    deleted = await engine.invalidate(entry_filter, allow_all=request.all)
    return {"dry_run": False, "deleted": deleted, "filter": applied}
